### ISSUE TITLE
Add support for CloudFormation and/or Elastic Beanstalk

### ISSUE THREAD

**Issue by rjbohinski** [TomOrth/BudgetReport#5]
To make installation easier you can add support for [Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/) or [CloudFormation](
https://aws.amazon.com/cloudformation/).

If you would like I could make a pull request with the configuration files.

**Comment by TomOrth** [comment]
I looked into elastic beanstalk, the part I couldn't figure out was making it work with docker-compose. If you want to make a PR for it, it would be greatly appreciated!
